Repository sillsdev/libpalaso, pull requests merged in 2025-03, with the labels that each got.

#1401 SP-2353 ContributorsListControl thread safety improvements
  CHANGELOG.md
  Palaso.sln.DotSettings
  SIL.Windows.Forms.WritingSystems.Tests/Tree/WritingSystemVariantSuggestorTests.cs
  SIL.Windows.Forms/ClearShare/ContributorsListControlViewModel.cs
  SIL.Windows.Forms/ClearShare/WinFormsUI/ContributorsListControl.cs
  SIL.Windows.Forms/ClearShare/WinFormsUI/ContributorsListControl.designer.cs
  SIL.Windows.Forms/Extensions/ControlExtensions.cs
  SIL.Windows.Forms/Widgets/BetterGrid/BetterGrid.cs
  SIL.WritingSystems.Tests/IetfLanguageTagTests.cs
  SIL.WritingSystems/Subtag.cs
  TestApps/SIL.Windows.Forms.TestApp/ContributorsForm.Designer.cs
  TestApps/SIL.Windows.Forms.TestApp/ContributorsForm.cs
  TestApps/SIL.Windows.Forms.TestApp/ContributorsForm.resx
Labels: bug, enhancement, api change

#1399 Changed StandardSubtags.AddLanguage to add the new entry to the Iso3Languages dictionary
  SIL.WritingSystems/IetfLanguageTag.cs
  SIL.WritingSystems/LdmlDataMapper.cs
  SIL.WritingSystems/Sldr.cs
  SIL.WritingSystems/StandardSubtags.cs
Labels: enhancement

#1404 Made some methods static in ConsoleErrorReporter
  CHANGELOG.md
  SIL.Core.Tests/Reporting/ConsoleErrorReporterTests.cs
  SIL.Core/Reporting/ConsoleErrorReporter.cs
  SIL.Core/Reporting/ExceptionHelper.cs
  SIL.Windows.Forms/Reporting/ExceptionReportingDialog.cs
Labels: low priority

#1410 Now that L10nsharp 8.0.0 is released, removed beta
  SIL.Windows.Forms.Keyboarding.Tests/SIL.Windows.Forms.Keyboarding.Tests.csproj
  SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
  SIL.Windows.Forms.Tests/SIL.Windows.Forms.Tests.csproj
  SIL.Windows.Forms/SIL.Windows.Forms.csproj
Labels: dependencies

#1407 Made it possible in VerseControl to handle tabbing out of verse porti…
  .editorconfig
  CHANGELOG.md
  Palaso.sln.DotSettings
  SIL.Windows.Forms.Scripture/SIL.Windows.Forms.Scripture.csproj
  SIL.Windows.Forms.Scripture/ToolStripVerseControl.cs
  SIL.Windows.Forms.Scripture/VerseControl.cs
  SIL.Windows.Forms/Widgets/EnterTextBox.cs
  TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp.csproj
  TestApps/SIL.Windows.Forms.TestApp/ScrReferenceFilterDlg.Designer.cs
  TestApps/SIL.Windows.Forms.TestApp/ScrReferenceFilterDlg.cs
  TestApps/SIL.Windows.Forms.TestApp/ScrReferenceFilterDlg.resx
  TestApps/SIL.Windows.Forms.TestApp/TestAppForm.Designer.cs
  TestApps/SIL.Windows.Forms.TestApp/TestAppForm.cs
Labels: enhancement, api change

#1412 Fix 'Redundant Select' & 'Useless upcast' warnings
  SIL.Windows.Forms.WritingSystems/WSTree/WritingSystemTreeModel.cs
  SIL.Windows.Forms/FileDialogExtender/HelperTypes.cs
  SIL.Windows.Forms/Widgets/BetterGrid/BetterGrid.cs
  SIL.WritingSystems/Migration/WritingSystemsLdmlV0To1Migration/FlexConformPrivateUseRfc5646TagInterpreter.cs
Labels: low priority

#1414 [SIL.DictionaryServices] Add Fields to LexEntry
  CHANGELOG.md
  SIL.DictionaryServices.Tests/Lift/LiftRoundTripTests.cs
  SIL.DictionaryServices.Tests/Lift/LiftWriterTests.cs
  SIL.DictionaryServices.Tests/Model/LexEntryTests.cs
  SIL.DictionaryServices/Lift/LiftWriter.cs
  SIL.DictionaryServices/Model/LexEntry.cs
  SIL.Lift.Tests/Parsing/ParserTests.cs
  SIL.Lift.Tests/test20080407.lift
Labels: enhancement, api change

#1415 Incremental step toward upgrading DLLs
  ExtractCopyright.Tests/ExtractCopyright.Tests.csproj
  SIL.Archiving.Tests/SIL.Archiving.Tests.csproj
  SIL.Archiving/SIL.Archiving.csproj
  SIL.Core.Desktop.Tests/SIL.Core.Desktop.Tests.csproj
  SIL.Core.Desktop/SIL.Core.Desktop.csproj
  SIL.Core.Tests/SIL.Core.Tests.csproj
  SIL.Core/SIL.Core.csproj
  SIL.DblBundle.Tests/SIL.DblBundle.Tests.csproj
  SIL.DictionaryServices.Tests/SIL.DictionaryServices.Tests.csproj
  SIL.Lexicon.Tests/SIL.Lexicon.Tests.csproj
  SIL.Lift.Tests/SIL.Lift.Tests.csproj
  SIL.Lift/SIL.Lift.csproj
  SIL.Linux.Logging.Tests/SIL.Linux.Logging.Tests.csproj
  SIL.Media.Tests/SIL.Media.Tests.csproj
  SIL.Media/SIL.Media.csproj
  SIL.Scripture.Tests/SIL.Scripture.Tests.csproj
  SIL.Scripture/SIL.Scripture.csproj
  SIL.TestUtilities.Tests/SIL.TestUtilities.Tests.csproj
  SIL.TestUtilities/SIL.TestUtilities.csproj
  SIL.Windows.Forms.Archiving/SIL.Windows.Forms.Archiving.csproj
  SIL.Windows.Forms.DblBundle/SIL.Windows.Forms.DblBundle.csproj
  SIL.Windows.Forms.Keyboarding.Tests/SIL.Windows.Forms.Keyboarding.Tests.csproj
  SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
  SIL.Windows.Forms.Scripture.Tests/SIL.Windows.Forms.Scripture.Tests.csproj
  SIL.Windows.Forms.Scripture/SIL.Windows.Forms.Scripture.csproj
  SIL.Windows.Forms.Tests/SIL.Windows.Forms.Tests.csproj
  SIL.Windows.Forms.WritingSystems.Tests/SIL.Windows.Forms.WritingSystems.Tests.csproj
  SIL.Windows.Forms.WritingSystems/SIL.Windows.Forms.WritingSystems.csproj
  SIL.Windows.Forms/SIL.Windows.Forms.csproj
  SIL.WritingSystems.Tests/SIL.WritingSystems.Tests.csproj
  SIL.WritingSystems/SIL.WritingSystems.csproj
Labels: dependencies

#1400 Remove useless variable assignments
  SIL.Core.Desktop.Tests/Network/RobustNetworkOperation.Tests.cs
  SIL.Core.Desktop.Tests/UsbDrive/UsbDeviceInfoTests.cs
  SIL.Core.Desktop.Tests/i18n/StringCatalogTests.cs
  SIL.Core.Desktop/Settings/CrossPlatformSettingsProvider.cs
  SIL.Core.Desktop/i18n/StringCatalog.cs
  SIL.Core.Tests/Migration/XmlReaderWriterMigratorTests.cs
  SIL.Core.Tests/Migration/XslMigratorTests.cs
  SIL.Core.Tests/Spelling/WordTokenizerTests.cs
  SIL.Core.Tests/Xml/FastXmlElementSplitterTests.cs
  SIL.Core/ClearShare/Contribution.cs
  SIL.Core/ClearShare/OlacSystem.cs
  SIL.Core/Reporting/UsageReporter.cs
  SIL.Core/Xml/XmlUtils.cs
  SIL.DictionaryServices.Tests/LexEntryRepositoryTests.cs
  SIL.DictionaryServices.Tests/Lift/LexEntryFromLiftBuilderTests.cs
  SIL.DictionaryServices.Tests/Model/LexEntryTests.cs
  SIL.Lift.Tests/Merging/LiftChangeDetectorTests.cs
  SIL.Lift.Tests/Merging/xmldiff/XmlDiffTests.cs
  SIL.Lift/Merging/LiftChangeDetector.cs
  SIL.TestUtilities.Tests/TemporaryFolderTests.cs
  SIL.Windows.Forms.GeckoBrowserAdapter/GeckoBase.cs
  SIL.Windows.Forms.GeckoBrowserAdapter/ReflectiveGeckoBrowser.cs
  SIL.Windows.Forms.Keyboarding/Linux/IbusDefaultEventHandler.cs
  SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardAdaptor.cs
  SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs
  SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardDescription.cs
  SIL.Windows.Forms.Tests/ImageToolbox/PalasoImageTests.cs
  SIL.Windows.Forms.Tests/SettingsProviderTests.cs
  SIL.Windows.Forms/ClearShare/LicenseInfo.cs
  SIL.Windows.Forms/ClearShare/Metadata.cs
  SIL.Windows.Forms/ImageToolbox/ImageAcquisitionService.cs
  SIL.Windows.Forms/ImageToolbox/PalasoImage.cs
  SIL.Windows.Forms/PropertyBag-NoTests/FilePathEditor.cs
  SIL.Windows.Forms/Proxy/ProxyCredentialsRequestDialog.cs
  SIL.WritingSystems/Migration/WritingSystemsLdmlV0To1Migration/XmlHelpersV0.cs
  TestApps/FastSplitterTest/Form1.cs
Labels: low priority
