Repository sillsdev/libpalaso, pull requests merged in 2025-02, with the labels that each got.

#1375 Made FadingMessageWindow implement all UI logic on the UI thread
  CHANGELOG.md
  SIL.Windows.Forms/ClearShare/WinFormsUI/ContributorsListControl.cs
  SIL.Windows.Forms/ClearShare/WinFormsUI/FadingMessageForm.cs
  TestApps/SIL.Windows.Forms.TestApp/TestAppForm.Designer.cs
  TestApps/SIL.Windows.Forms.TestApp/TestAppForm.cs
  TestApps/SIL.Windows.Forms.TestApp/TestAppForm.resx
Labels: bug, fix

#1381 Fix checks for null or empty array
  SIL.Media/AlsaAudio/RecordingDevice.cs
  SIL.Windows.Forms/Progress/LogBox.cs
Labels: fix

#1385 Fix double-semicolons
  SIL.Archiving/IMDI/Schema/IMDI_3_0.cs
  SIL.Core/Reporting/AnalyticsEventSender.cs
  SIL.Core/Reporting/ConsoleErrorReporter.cs
  SIL.DictionaryServices/Processors/EntryMerger.cs
  SIL.Windows.Forms.GeckoBrowserAdapter/ReflectiveGeckoBrowser.cs
  SIL.Windows.Forms/Widgets/BitmapButton.cs
Labels: low priority

#1377 Removed old 2014 version of SIL logo from artwork folder.
  artwork/SIL_Logo_2014_TM_Color_no_bleed_tag_.svg
Labels: low priority

#1383 +semver:major Download langtags with etag
  CHANGELOG.md
  SIL.WritingSystems.Tests/SldrTests.cs
  SIL.WritingSystems/Sldr.cs
Labels: enhancement

#1390 [SIL.Windows.Forms.Archiving] Remove DotNetZip acknowledgement
  SIL.Windows.Forms.Archiving/Properties/AssemblyInfo.cs
Labels: low priority, documentation

#1384 Use with open to ensure files close
  SIL.Archiving/IMDI/Schema/IMDI_3_0_Fix.py
Labels: low priority

#1371 Added a unit test for XmlSerializationHelper.SerializeToString and did minor code cleanup
  CHANGELOG.md
  SIL.Core.Tests/Extensions/StringExtensionTests.cs
  SIL.Core.Tests/Xml/XmlSerializationHelperTests.cs
  SIL.Core/Extensions/StringExtensions.cs
  SIL.Core/Progress/ConsoleProgress.cs
  SIL.Core/Progress/GenericProgress.cs
  SIL.Core/Xml/XmlSerializationHelper.cs
  SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardRetrievingAdaptor.cs
  SIL.Windows.Forms.WritingSystems/WritingSystemSetupModel.cs
  SIL.WritingSystems/Migration/IcuRulesParser.cs
  SIL.WritingSystems/SimpleRulesParser.cs
  SIL.WritingSystems/StandardSubtags.cs
Labels: low priority

#1391 [SIL.Archiving.Tests] Run IMDIArchivingDlgViewModelTests tests that failed on TeamCity
  SIL.Archiving.Tests/IMDIArchivingDlgViewModelTests.cs
Labels: low priority

#1389 +semver:major [SIL.WritingSystems] Add UI font role
  CHANGELOG.md
  SIL.WritingSystems.Tests/GlobalWritingSystemRepositoryTests.cs
  SIL.WritingSystems.Tests/LdmlDataMapperTests.cs
  SIL.WritingSystems.Tests/Migration/LdmlInFolderWritingSystemRepositoryMigratorTests.cs
  SIL.WritingSystems/FontDefinition.cs
  SIL.WritingSystems/LdmlDataMapper.cs
Labels: enhancement, fix

#1396 [SIL.Windows.Forms.Widgets] Fix loss of precision in HorizontalSpinner.DrawArrow
  CHANGELOG.md
  SIL.Windows.Forms/Widgets/HorizontalSpinner.cs
Labels: low priority, fix

#1395 Add explicit GHA workflow permissions
  .github/workflows/build.yml
  .github/workflows/l10n-packaging.yml
  .github/workflows/l10n-source.yml
Labels: low priority
